name: Build and Upload Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore Dependencies
      run: msbuild AtlasToolbox-WinUI3.sln /t:restore /p:Platform="x64"

    - name: Build Solution
      run: msbuild AtlasToolbox-WinUI3.sln /p:Configuration=Release /p:Platform="x64"

    - name: Publish Application
      run: msbuild AtlasToolbox-WinUI3.sln /t:Publish /p:Configuration=Release /p:Platform="x64" /p:PublishDir="D:\a\atlas-toolbox\atlas-toolbox\Deploy\src\"

    # - name: Build IsWiX Installer
    #   run: dotnet build D:\a\atlas-toolbox\atlas-toolbox\Installer\ToolboxPackaging.wixproj --configuration Release -p:DefineConstants="MSIProductVersion=1.0.0" --output "D:\a\atlas-toolbox\atlas-toolbox\artifacts\"

    - name: Compile .ISS to .EXE Installer
      uses: zhuzichu520/inno-setup-action@v1.0.0
      with:
        filepath: Installer/setup.iss
        
    - name: List Directory Structure After MSI Build
      run: dir "D:\a\atlas-toolbox\atlas-toolbox\artifacts\"

    - name: Create ZIP of MSI
      run: powershell Compress-Archive -Path "D:\a\atlas-toolbox\atlas-toolbox\artifacts\*" -DestinationPath "D:\a\atlas-toolbox\atlas-toolbox\AtlasToolbox.zip"

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AtlasToolbox
        path: D:\a\atlas-toolbox\atlas-toolbox\AtlasToolbox.zip
